accounts:
  - name: alice
    coins: ["200000000rio"]
  - name: bob
    coins: ["100000000rio"]
validator:
  name: alice
  staked: "100000000rio"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob
  host: ":4501"
  coins: ["1000rio"]
genesis:
  chain_id: "network-test2"
  app_state:
    staking:
      params:
        bond_denom: "rio"
    mint:
      params:
        mint_denom: "rio"
    crisis:
      constant_fee:
        denom: "rio"
host:
  rpc: ":26659"
  p2p: ":26658"
  prof: ":6061"
  grpc: ":9092"
  grpc-web: ":9093"
  api: ":1318"
  frontend: ":8081"
  dev-ui: ":12346"
init:
  home: "$HOME/.network2"

