accounts:
  - name: eduardo
    coins: ["80000000000000urio"]
  - name: aaron
    coins: ["20000000000000urio"]
validator:
  name: eduardo
  staked: "20000000000000urio"
client:
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: eduardo
  coins: ["1000000000urio"]
genesis:
  chain_id: "realionetwork-local"
  app_state:
    staking:
      params:
        bond_denom: "urio,rst"
        historical_entries: "10"
        max_validators: "10"
        unbonding_time: "10000000000ns"
    mint:
      params:
        mint_denom: "urio"
    crisis:
      constant_fee:
        denom: "urio"


